language: csharp
compiler:
    gcc
    clang

before_install:
    - sudo apt-get install libevent-dev

script:
    - echo $CC $CXX
    - ./autogen.sh --prefix=/usr
    - make
    - sudo make install

